local PushButtons =  {}

PushButtons.All = {
    'Tap',
    'Metronome',
    'Master',
    'Stop',
    'Left',
    'Right',
    'Up',
    'Down',
    'Select',
    'Shift',
    'Note',
    'Session',
    'AddEffect',
    'AddTrack',
    'OctaveDown',
    'OctaveUp',
    'Repeat',
    'Accent',
    'Scales',
    'UserMode',
    'Mute',
    'Solo',
    'DeviceLeft',
    'DeviceRight',
    'Play',
    'Record',
    'New',
    'Duplicate',
    'Automation',
    'FixedLength',
    'Device',
    'Browse',
    'Track',
    'Clip',
    'Volume',
    'PanSend',
    'Quantize',
    'Double',
    'Delete',
    'Undo'
}

PushButtons.MidiMap = {
    Tap = 3,
    Metronome = 9,
    Master = 28,
    Stop = 29,
    Left = 44,
    Right = 45,
    Up = 46,
    Down = 47,
    Select = 48,
    Shift = 49,
    Note = 50,
    Session = 51,
    AddEffect = 52,
    AddTrack = 53,
    OctaveDown = 54,
    OctaveUp = 55,
    Repeat = 56,
    Accent = 57,
    Scales = 58,
    UserMode = 59,
    Mute = 60,
    Solo = 61,
    DeviceLeft = 62,
    DeviceRight = 63,
    Play = 85,
    Record = 86,
    New = 87,
    Duplicate = 88,
    Automation = 89,
    FixedLength = 90,
    Device = 110,
    Browse = 111,
    Track = 112,
    Clip = 113,
    Volume = 114,
    PanSend = 115,
    Quantize = 116,
    Double = 117,
    Delete = 118,
    Undo = 119
}

PushButtons.States = { Off = 0, On = 1, Hi = 4 }

return PushButtons
