-- Adapted from Push4Bitwig
-- https://github.com/git-moss/Push4Bitwig

local PushColors = {}

--- PushColors.PadColors : colors for grid pads and second row ( State Control row )
--
PushColors.PadColors = {
    Black = 0,
    GreyLo = 1,
    GreyMd = 2,
    White = 3,
    Rose = 4,
    RedHi = 5,
    Red = 6,
    RedLo = 7,
    RedAmber = 8,
    AmberHi = 9,
    Amber = 10,
    AmberLo = 11,
    AmberYellow = 12,
    YellowHi = 13,
    Yellow = 14,
    YellowLo = 15,
    YellowLime = 16,
    LimeHi = 17,
    Lime = 18,
    LimeLo = 19,
    LimeGreen = 20,
    GreenHi = 21,
    Green = 22,
    GreenLo = 23,
    GreenSpring = 24,
    SpringHi = 25,
    Spring = 26,
    SpringLo = 27,
    SpringTurquoise = 28,
    TurquoiseLo = 29,
    Turquoise = 30,
    TurquoiseHi = 31,
    TurquoiseCyan = 32,
    CyanHi = 33,
    Cyan = 34,
    CyanLo = 35,
    CyanSky = 36,
    SkyHi = 37,
    Sky = 38,
    SkyLo = 39,
    SkyOcean = 40,
    OceanHi = 41,
    Ocean = 42,
    OceanLo = 43,
    OceanBlue = 44,
    BlueHi = 45,
    Blue = 46,
    BlueLo = 47,
    BlueOrchid = 48,
    OrchidHi = 49,
    Orchid = 50,
    OrchidLo = 51,
    OrchidMagenta = 52,
    MagentaHi = 53,
    Magenta = 54,
    MagentaLo = 55,
    MagentaPink = 56,
    PinkHi = 57,
    Pink = 58,
    PinkLo = 59,
}

--- PushColors.TopRowColors : colors for the first row ( selection control )
--
PushColors.TopRowColors = {
    Black = 0,
    RedLo = 1,
    RedLoBlink = 2,
    RedLoBlinkFast = 3,
    RedHi = 4,
    RedHiBlink = 5,
    RedHiBlinkFast = 6,
    OrangeLo = 7,
    OrangeLoBlink = 8,
    OrangeLoBlinkFast = 9,
    OrangeHi = 10,
    OrangeHiBlink = 11,
    OrangeHiBlinkFast = 12,
    YellowLo = 13,
    YellowLoBlink = 14,
    YellowLoBlinkFast = 15,
    YellowMd = 16,
    YellowMdBlink = 17,
    YellowMdBlinkFast = 18,
    GreenLo = 19,
    GreenLoBlink = 20,
    GreenLoBlinkFast = 21,
    GreenHi = 22,
    GreenHiBlink = 23,
    GreenHiBlinkFast = 24,
}
--- PushColors.SceneColors : colors for the scene ( vertical right ) buttons
PushColors.SceneColors = {
    Red = 1,
    RedBlink = 2,
    RedBlinkFast = 3,
    RedHi = 4,
    RedHiBlink = 5,
    RedHiBlinkFast = 6,
    Orange = 7,
    OrangeBlink = 8,
    OrangeBlinkFast = 9,
    OrangeHi = 10,
    OrangeHiBlink = 11,
    OrangeHiBlinkFast = 12,
    Yellow = 13,
    YellowBlink = 14,
    YellowBlinkFast = 15,
    YellowHi = 16,
    YellowHiBlink = 17,
    YellowHiBlinkFast = 18,
    Green = 19,
    GreenBlink = 20,
    GreenBlinkFast = 21,
    GreenHi = 22,
    GreenHiBlink = 23,
    GreenHiBlinkFast = 24,
}

return PushColors
